[build]
  command = "rm -rf node_modules .next out package-lock.json && npm install --no-optional --legacy-peer-deps && NEXT_TELEMETRY_DISABLED=1 NEXT_SKIP_TYPECHECKING=true NODE_OPTIONS='--max_old_space_size=4096 --no-compilation-cache' npm run build"
  publish = "out"

[build.environment]
  MONGODB_URI = "mongodb://dummy-value-for-build-only:27017/test"
  ADMIN_USERNAME = "admin"
  ADMIN_PASSWORD = "password"
  NEXT_PUBLIC_ADMIN_USERNAME = "admin"
  NEXT_PUBLIC_ADMIN_PASSWORD = "password"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Turn off Next.js plugin to avoid SWC issues
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Optimize memory usage during build
  NODE_OPTIONS = "--max_old_space_size=4096 --no-compilation-cache"
  # Skip SWC and use Babel instead
  NEXT_SKIP_SWC = "1"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data: https://*.openweathermap.org https://unpkg.com blob:; connect-src 'self' https://*.openweathermap.org https://api.rainviewer.com; frame-src 'self'; font-src 'self';" 