[build]
  command = "bash ./build.sh"
  publish = "out"

[build.environment]
  MONGODB_URI = "mongodb://dummy-value-for-build-only:27017/test"
  ADMIN_USERNAME = "admin"
  ADMIN_PASSWORD = "password"
  NEXT_PUBLIC_ADMIN_USERNAME = "admin"
  NEXT_PUBLIC_ADMIN_PASSWORD = "password"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Turn off Next.js plugin to avoid SWC issues
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Skip SWC and use Babel instead
  NEXT_SKIP_SWC = "1"
  # Don't set NODE_OPTIONS here to avoid the flag error

# Redirect all paths to the main site
[[redirects]]
  from = "/*"
  to = "https://warningtest.oragewx.site/:splat"
  status = 301
  force = true

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://warningtest.oragewx.site; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data: https://*.openweathermap.org https://unpkg.com blob:; connect-src 'self' https://*.openweathermap.org https://api.rainviewer.com; frame-src 'self'; font-src 'self';" 