[build]
  command = "npm install && mv tsconfig.json tsconfig.json.backup && NODE_OPTIONS=--max_old_space_size=4096 NEXT_SKIP_TYPE_CHECK=true NEXT_TELEMETRY_DISABLED=1 npx next build --no-lint && mv tsconfig.json.backup tsconfig.json"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.10.0"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  TYPESCRIPT_SKIP_CHECKING = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 