[build]
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && NEXT_PUBLIC_SKIP_TYPE_CHECK=true npm run build"
  publish = ".next"

[build.environment]
  MONGODB_URI = "mongodb://dummy-value-for-build-only:27017/test"
  ADMIN_USERNAME = "admin"
  ADMIN_PASSWORD = "password"
  NEXT_PUBLIC_ADMIN_USERNAME = "admin"
  NEXT_PUBLIC_ADMIN_PASSWORD = "password"
  NODE_VERSION = "18.20.0"
  NEXT_TELEMETRY_DISABLED = "1"
  # Skip Netlify Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data: https://*.openweathermap.org https://unpkg.com blob:; connect-src 'self' https://*.openweathermap.org https://api.rainviewer.com; frame-src 'self'; font-src 'self';" 