[build]
  command = "npm i --force && npm i --save-dev typescript@latest @types/react@latest @types/node@latest --force && NODE_OPTIONS=--max_old_space_size=4096 npx next build --no-lint"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.10.0"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  TYPESCRIPT_SKIP_CHECKING = "true"
  NEXT_IGNORE_TYPE_ERROR = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 