[build]
  command = "node build-static.js"
  publish = "out"

[build.environment]
  MONGODB_URI = "mongodb://dummy-value-for-build-only:27017/test"
  ADMIN_USERNAME = "admin"
  ADMIN_PASSWORD = "password"
  NEXT_PUBLIC_ADMIN_USERNAME = "admin"
  NEXT_PUBLIC_ADMIN_PASSWORD = "password"
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data: https://*.openweathermap.org https://unpkg.com blob:; connect-src 'self' https://*.openweathermap.org https://api.rainviewer.com; frame-src 'self'; font-src 'self';" 