[build]
  command = "npm install && npm install --save-dev typescript @types/react @types/node && npx next build --no-lint"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.10.0"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  TYPESCRIPT_SKIP_CHECKING = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 